server:
  port: 8080
  servlet:
    context-path: /tk

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
ws:
  port: 9600
  title: ws服务器
  host: 0.0.0.0
  boss-count: 1
  work-count: 100
  allow-custom-requests: true
  upgrade-timeout: 10000
  ping-timeout: 60000
  ping-interval: 25000